name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "content": "@zvckool",
            "embeds": [{
              "title": "PR Inbound 👀",
              "url": "'"${{ github.event.pull_request.html_url }}"'",
              "color": 5814783,
              "fields": [
                {
                  "name": "Author",
                  "value": "'"${{ github.event.pull_request.user.login }}"'",
                  "inline": false
                },
                {
                  "name": "Branch",
                  "value": "'"${{ github.event.pull_request.head.ref }}"' → '"${{ github.event.pull_request.base.ref }}"'",
                  "inline": false
                },
                {
                  "name": "Repository",
                  "value": "'"${{ github.repository }}"'",
                  "inline": false
                }
              ],
            }]
          }' \
          $DISCORD_WEBHOOK_URL